apiVersion: v1
kind: PersistentVolume
metadata:
  name: x11-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/.X11-unix/"

